site_name: Elvis Soares
site_description: Research & teaching in molecular engineering, soft matter, simulations
# site_url: https://elvissoares.github.io/<repo-name>/
# repo_url: https://github.com/elvissoares/<repo-name>
theme:
  name: material
  language: pt
  palette:
    - scheme: slate           # dark mode
      primary: navy         # main brand color
      accent: navy          # highlight color
      toggle:
        icon: material/weather-sunny
        name: Change to Lighter
    - scheme: default         # light (fallback)
      primary: navy
      accent: navy
      toggle:
        icon: material/weather-night
        name: Change to Darker
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate

nav:
  - About Me: index.md
  - Research: research.md
  - Teaching: teaching.md
  - Publication: publications.md
  - Blog:
      - blog/index.md

plugins:
  - search
  - blog: {}        # blog plugin built into Material
  # (optional) BibTeX citations for the Publications page:
  # - bibtex:
  #     bib_file: refs.bib

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elvissoares
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/<your-handle>/
